### ISSUE TITLE
Ethereumの練習

### ISSUE THREAD

**Issue by soudegesu** [soudegesu/blog#52]
開発者向けコミュニティに入るために頑張る
https://qiita.com/amachino/items/605ff76209d7193dc92c

**Comment by soudegesu** [comment]
入るためには `Ropsten` の 1Ethが必要らしいので取りに行く

**Comment by soudegesu** [comment]
`Metamask` がいろんなサイトで紹介されているけど、パクられたらやなので、普段使いじゃない
FireFoxにpluginをインストールする

**Comment by soudegesu** [comment]
パスワードと12単語をコピって保存しておく

**Comment by soudegesu** [comment]
Ropsten Testネットで `Buy` する

**Comment by soudegesu** [comment]
`「request 1 ether from faucet」` を押して拝借する

**Comment by soudegesu** [comment]
getできたので 開発者コミュに入れた

**Comment by soudegesu** [comment]
教材は何がよいだろうか
http://block-chain.jp/tech/ethereum-learning-for-engineer/

**Comment by soudegesu** [comment]
やっぱudemyか

**Comment by soudegesu** [comment]
Gethをインストールする

**Comment by soudegesu** [comment]
```
brew tap ethereum/ethereum
brew install ethereum
```

**Comment by soudegesu** [comment]
プライベートネットを作成する
```
mkdir ~/workspace/eth_private_net
```

**Comment by soudegesu** [comment]
jsonファイルを作成する.

```
{
  "config": {
    "chainId": 15
  },
  "nonce": "0x0000000000000042",
  "timestamp": "0x0",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "extraData": "",
  "gasLimit": "0x8000000",
  "difficulty": "0x4000",
  "mixhash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "coinbase": "0x3333333333333333333333333333333333333333",
  "alloc": {}
}
```

ブロックチェーン情報の初期化
```
geth --datadir ~/workspace/eth_private_net init ~/workspace/eth_private_net/myGenesis.json
```

**Comment by soudegesu** [comment]
こんなのが出た
```
INFO [02-26|16:35:29] Maximum peer count                       ETH=25 LES=0 total=25
INFO [02-26|16:35:29] Allocated cache and file handles         database=/Users/takaaki-suzuki/workspace/eth_private_net/geth/chaindata cache=16 handles=16
INFO [02-26|16:35:29] Writing custom genesis block
INFO [02-26|16:35:29] Persisted trie from memory database      nodes=0 size=0.00B time=13.347µs gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
INFO [02-26|16:35:29] Successfully wrote genesis state         database=chaindata                                                      hash=7b2e8b…7e0432
INFO [02-26|16:35:29] Allocated cache and file handles         database=/Users/takaaki-suzuki/workspace/eth_private_net/geth/lightchaindata cache=16 handles=16
INFO [02-26|16:35:29] Writing custom genesis block
INFO [02-26|16:35:29] Persisted trie from memory database      nodes=0 size=0.00B time=2.303µs  gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
INFO [02-26|16:35:29] Successfully wrote genesis state         database=lightchaindata                                                      hash=7b2e8b…7e0432
```

**Comment by soudegesu** [comment]
通常の通貨のトランザクションは
* origin
* destination
* date
* amount
があればOK

**Comment by soudegesu** [comment]
`hold on your hat` 驚かないでね。(乞うご期待的な意味)

**Comment by soudegesu** [comment]
`UTXO` という仕組みがある
http://gaiax-blockchain.com/utxo

**Comment by soudegesu** [comment]
`Ethereum` はUTXOを使っていないのか

**Comment by soudegesu** [comment]
`Ethereum` は `Proof of Stake` を採用しているらしい
https://coinotaku.com/?p=1302

**Comment by soudegesu** [comment]
大きく２つあるらしい
* `Proof of work` に Coin Ageの概念を追加したもの
  * Coin Ageが大きい程マイニングが成功しやすい。一度マイニングが成功するとCoin Ageが減る(1つの組織がマイニングを牛耳れない)
* コインの保有数に依存するもの
 * 取引を承認する人をランダムに決める際に、選ばれる確立をコインの保有量に比例させておく
 * マイニングではなく `フォージング` と呼ばれる

**Comment by soudegesu** [comment]
Ethereum は今はProof of work を採用しているが将来的には `Proof of Stake` に以降する。
でも予定は未定。
段階的アプデートが提唱されていて、以下のようなプロジェクトが存在する。
* Frontier(フロンティア)
* Homestead(ホームステッド)
* Metropolis(メトロポリス)
* Serenity (セレニティ)
今は Byzantium(ビザンチウム)

**Comment by soudegesu** [comment]
```
Proof of WorkからProof of Stakeに移行する際にマイナーがProof of Workを採用しているブロックチェーンに残り続けないように、ディフィカルティボムという仕組みが予め定められていました。このデフィカルティボムは、Proof of Workのままではマイナーの採算が合わなくなるように、マイニングの難易度を徐々に上げていくというものです。
```

**Comment by soudegesu** [comment]
Ethereum 上でのPoSの実装が `Casper` で 不正なトランザクションを 承認した場合に与える罰としての仕組みとして `Slasher` も提案されている

**Comment by soudegesu** [comment]
マイニング承認システム と トランザクションアルゴリズム を注目すると良い

**Comment by soudegesu** [comment]
3layer model
* instances
  * どこに公開するかを決める(Main netなのか、Test netなのか)
* implementations
  * 何で作るかを決める(Ethなのか、Bitcoinなのか)
* design goal
  * 作る目的を決める(非中央集権化なのか、配布して流通させることなのか、データの保存なのか)

**Comment by soudegesu** [comment]
`INFURA` っていうサービスがあるのか。知らなかった。

**Comment by soudegesu** [comment]
pseudonymity: 偽名

**Comment by soudegesu** [comment]
Bitcoinは1MB/blockなため4トランザクション/s, 4million gasのためEthは 20トランザクション/s

**Comment by soudegesu** [comment]
Visaカードは40000トランザクション/sでさばいているからそれに比べるとしょぼい

**Comment by soudegesu** [comment]
Ethのマークル木
https://easythereentropy.wordpress.com/2014/06/04/understanding-the-ethereum-trie/

**Comment by soudegesu** [comment]
ganache はエミュレータらしい

**Comment by soudegesu** [comment]
以下を実行する
```
puppeth
```

**Comment by soudegesu** [comment]
NetworkNameを決める
```
ChainSkills
```

**Comment by soudegesu** [comment]
GenesisBlockを作成する `2` を入力

**Comment by soudegesu** [comment]
```
Which consensus engine to use? (default = clique)
 1. Ethash - proof-of-work
 2. Clique - proof-of-authority
```

PoWのどのアルゴリズムを採用するか選ぶ。今回は `1`

**Comment by soudegesu** [comment]
アカウントは何も押さずにEnter
```
Which accounts should be pre-funded? (advisable at least one)
> 0x
```

**Comment by soudegesu** [comment]
使うNetworkIDは
```
1がMainnet
2がMorden test net(obsolete)
3がRopsten test net
4がRinkeby test net
42がKovan test net 
```

**Comment by soudegesu** [comment]
今回は `4224` とする

**Comment by soudegesu** [comment]
```
What would you like to do? (default = stats)
 1. Show network stats
 2. Manage existing genesis
 3. Track new remote server
 4. Deploy network components
> 2
```

**Comment by soudegesu** [comment]
```
 1. Modify existing fork rules
 2. Export genesis configuration
 3. Remove genesis configuration
> 2
```

**Comment by soudegesu** [comment]
```
Which file to save the genesis into? (default = ChainSkills.json)
>
INFO [03-03|06:09:57] Exported existing genesis block
```

**Comment by soudegesu** [comment]
ここまで来ると1周するので `Cntl + C` でExitする

**Comment by soudegesu** [comment]
`ChainSkills.json` が出来ている

**Comment by soudegesu** [comment]
`config` ブロックがChainのパラメータ
```
config: {
    "chainId": 4224,
    "homesteadBlock": 1,
    "eip150Block": 2,
    "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "eip155Block": 3,
    "eip158Block": 3,
    "byzantiumBlock": 4,
    "ethash": {}
}
```

**Comment by soudegesu** [comment]
初期化をする
```
geth --datadir ./private init ./ChainSkills.json 
```

**Comment by soudegesu** [comment]
```
INFO [03-04|06:55:40] Maximum peer count                       ETH=25 LES=0 total=25
INFO [03-04|06:55:40] Allocated cache and file handles         database=/xxxx/private/truffle-test/private/geth/chaindata cache=16 handles=16
INFO [03-04|06:55:40] Writing custom genesis block
INFO [03-04|06:55:40] Persisted trie from memory database      nodes=354 size=65.02kB time=2.714835ms gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
INFO [03-04|06:55:40] Successfully wrote genesis state         database=chaindata         hash=5ef01e…4055b0
INFO [03-04|06:55:40] Allocated cache and file handles         database=/Users/takaaki-suzuki/private/truffle-test/private/geth/lightchaindata cache=16 handles=16
INFO [03-04|06:55:40] Writing custom genesis block
INFO [03-04|06:55:40] Persisted trie from memory database      nodes=354 size=65.02kB time=2.125845ms gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
INFO [03-04|06:55:40] Successfully wrote genesis state         database=lightchaindata              hash=5ef01e…4055b0
```

**Comment by soudegesu** [comment]
なんかファイルが更新された

**Comment by soudegesu** [comment]
```
geth --datadir . account new   
```

**Comment by soudegesu** [comment]
パスワード作成を要求されるので適当に打ち込む

**Comment by soudegesu** [comment]
addressが出てきた
```
Your new account is locked with a password. Please give a password. Do not forget this password.
Passphrase:
Repeat passphrase:
Address: {2f048cd640f7de2fbde6eb611884c0c1f57b28f0}
```

**Comment by soudegesu** [comment]
↑のコマンドを実行するたびにアカウントが作成できる

**Comment by soudegesu** [comment]
この段階で `keystore` ディレクトリを lsすると出て来る
```
#ls keystore 
UTC--2018-03-03T22-02-16.991865178Z--2f048cd640f7de2fbde6eb611884c0c1f57b28f0
```

**Comment by soudegesu** [comment]
持っているアカウントの一覧を表示
```
geth --datadir . account list 
INFO [03-04|07:05:50] Maximum peer count                       ETH=25 LES=0 total=25
Account #0: {2f048cd640f7de2fbde6eb611884c0c1f57b28f0} keystore:///xxxx/private/truffle-test/keystore/UTC--2018-03-03T22-02-16.991865178Z--2f048cd640f7de2fbde6eb611884c0c1f57b28f0
```

**Comment by soudegesu** [comment]
こんな感じのシェルを作成しておく
```
geth --networkid 4224 --mine --minerthreads 1 --datadir "~/private/truffle-test/private" --nodiscover --rpc --rpcport "8545" --port "30303" --rpccorsdomain "*" --nat "any" --rpcapi eth,web3,personal,net --unlock 0 --password ~/private/truffle-test/private/password.sec --ipcpath "~/Library/Ethereum/geth.ipc"
```

**Comment by soudegesu** [comment]
runする `./startnode.sh`

**Comment by soudegesu** [comment]
なんかwarningが出たのだが
```
INFO [03-04|09:23:02] RLPx listener up                         self="enode://c30516b7be66d532e0144013d8f0e355b6d33ba34ce012cb9dfeb4a443caa0584d590ecfa615d0b6605a13251362415ae31aa63bb733963e671ebcbe40cdd3b0@[::]:30303?discport=0"
INFO [03-04|09:23:02] IPC endpoint opened                      url=/Users/takaaki-suzuki/Library/Ethereum/geth.ipc
INFO [03-04|09:23:02] HTTP endpoint opened                     url=http://127.0.0.1:8545                           cors=* vhosts=localhost
WARN [03-04|09:23:02] -------------------------------------------------------------------
WARN [03-04|09:23:02] Referring to accounts by order in the keystore folder is dangerous!
WARN [03-04|09:23:02] This functionality is deprecated and will be removed in the future!
WARN [03-04|09:23:02] Please use explicit addresses! (can search via `geth account list`)
WARN [03-04|09:23:02] -------------------------------------------------------------------
```

**Comment by soudegesu** [comment]
`keystore` ディレクトリが別の所にできていたっぽい

**Comment by soudegesu** [comment]
もう一度試してみる
`./standnode.sh`

**Comment by soudegesu** [comment]
ハンマーマークが出てきたらマイニングができたやつらしい

**Comment by soudegesu** [comment]
うまくいかなくなってしまった場合には、`private` ディレクトリを1度削除して最初から処理をやり直せ、とのこと

**Comment by soudegesu** [comment]
mininngの主目的はトランザクションのマイニングではなく、あたらしい `Eth` を生成することである。

**Comment by soudegesu** [comment]
minerに対して新しいEthを割り当てる

**Comment by soudegesu** [comment]
次はこれを実行する
```
geth attach
```

**Comment by soudegesu** [comment]
javascriptコンソールが表示される

**Comment by soudegesu** [comment]
```
eth.accounts
> ["xxxxxxxxxxxxxxxxx", "yyyyyyyyyyyyyyyyy", "zzzzzzzzzzzzzz"]
```
アカウントが3つ出た

**Comment by soudegesu** [comment]
```
eth.coinbase
>"xxxxxxxxxxxxxxxxx"
```
マイニン時のメインアカウント

**Comment by soudegesu** [comment]
保有量を確認する(単位は`wei`)
```
> eth.getBalance(eth.accounts[0])
282000000000000000000
```

**Comment by soudegesu** [comment]
Eth表記にする場合は以下
```
web3.fromWei(eth.getBalance(eth.coinbase), "ether")
```

**Comment by soudegesu** [comment]
NetworkIDを確認したい場合
```
net.version
> 4224
```

**Comment by soudegesu** [comment]
```
> personal.unlockAccount(eth.accounts[1], "somepassword", 300)
true
```

**Comment by soudegesu** [comment]
トランザクションをサインする時にprivateKeyを利用可能にできる。
unlockでない間はトランザクションを送ることができない。

**Comment by soudegesu** [comment]
ここにgeth console利用時のコマンドが記載されている
https://github.com/ethereum/go-ethereum/wiki/JavaScript-Console

**Comment by soudegesu** [comment]
別アカウントに送金してみる
```
> eth.sendTransaction({from:eth.accounts[0], to:eth.accounts[1], value:web3.toWei(10, "ether")})
"some hash"
```

**Comment by soudegesu** [comment]
確認してみる
```
> web3.fromWei(eth.getBalance(eth.accounts[1]), "ether")
10
> web3.fromWei(eth.getBalance(eth.accounts[2]), "ether")
10
> web3.fromWei(eth.getBalance(eth.accounts[0]), "ether")
547
```

**Comment by soudegesu** [comment]
```
exit
```

**Comment by soudegesu** [comment]
MetaMaskはGanacheのテストネットワークと接続した後に、Mainnetに接続し、戻そうとすると、接続がうまくいかなくなるので、その場合には一度プラグインを無効にして、再度有効にしてから接続すると良い

**Comment by soudegesu** [comment]
「View account on Etherscan 」を使用するとMain net上のアカウントを確認できる

**Comment by soudegesu** [comment]
MetaMaskがJSONインポートできない場合はMetamaskのFAQを見るとよい
https://github.com/MetaMask/faq/blob/master/README.md#q-i-cant-use-the-import-feature-for-uploading-a-json-file-the-window-keeps-closing-when-i-try-to-select-a-file

**Comment by soudegesu** [comment]
`Viper` と `bamboo` と `solidity` が開発時のメジャーな言語
今回は `solidity`

**Comment by soudegesu** [comment]
Dappsの場合はWeb3.jsがEthereum nodeと接続するらしい

**Comment by soudegesu** [comment]
コンパイルしたらコレが出た
```
{ errors: [ 'No error reported, but compilation failed.' ],
  sourceList: [] }
```

`toString()` でテキストとして読み込んでいなかったから

**Comment by soudegesu** [comment]
`truffle init` 時に作成ｓあれる `contracts` ディレクトリは `solidity` の全てのcontractを含むディレクトリ

**Comment by soudegesu** [comment]
`migration` ディレクトリはデプロイ時に利用するコードが含まれている

**Comment by soudegesu** [comment]
`test` ディレクトリはテストスクリプトを配置する場所

**Comment by soudegesu** [comment]
`truffle.js` はtruffleの設定ファイル。デフォルトでは `Ganache` の `Ganache core` の設定を用いているため、カスタマイズする時に使う。
 `truffle-config.js` はWindowsのためにあるファイル

**Comment by soudegesu** [comment]
`truffle develop` で開きつつ別ターミナルで `truffle develop --log` をやる

**Comment by soudegesu** [comment]
``` 
migrate --compile-all --reset
```

**Comment by soudegesu** [comment]
logの方のターミナルを見てもログ出ないなぁ、これは後で確認しよう

**Comment by soudegesu** [comment]
`Greetings.address` を打ち込むとアドレスが表示される

**Comment by soudegesu** [comment]
`build/Greetings.json` の networkプロパティの中に `4447`がある。
これは `truffle` が作成したネットワーク

**Comment by soudegesu** [comment]
```
Greetings.deployed().then(function(instance){app = instance;})
```

**Comment by soudegesu** [comment]
`app`

**Comment by soudegesu** [comment]
```
app.setGreetings("Hello soudegesu!", {from:web3.eth.accounts[0]})
```

**Comment by soudegesu** [comment]
なんか `npm` でやっているのがあかん気がするので `scripts` で全部wrapしてしまおう

**Comment by soudegesu** [comment]
これを追加
```
"truffle-ganache": "truffle migrate --compile-all --reset --network ganache"
```

**Comment by soudegesu** [comment]
Balanceの後のETHの量が減っている。
トランザクションにより、gasが取られたから。

**Comment by soudegesu** [comment]
Gasについて
https://qiita.com/takeoworks/items/2fd008b1ce2fda473257

**Comment by soudegesu** [comment]
トランザクションを確認する。
ganacheからトランザクションハッシュをコピーして、以下を実行してみる
```
web3.eth.getTransaction("0x4c83faddddcccbe091e826184f7f0ac74ba3fa9a4abaee3609974dcdb8113234")

{ hash: '0x4c83faddddcccbe091e826184f7f0ac74ba3fa9a4abaee3609974dcdb8113234',
  nonce: 2,
  blockHash: '0x308ce73cf2786389d8fc8f30c96253542239ece8febf75ab4bdb3cb3b7c341c6',
  blockNumber: 3,
  transactionIndex: 0,
  from: '0x627306090abab3a6e1400e9345bc60c78a8bef57',
  to: '0x0',
  value: BigNumber { s: 1, e: 0, c: [ 0 ] },
  gas: 6721975,
  gasPrice: BigNumber { s: 1, e: 11, c: [ 100000000000 ] },
  input: '0x6060604052341561000f57600080fd5b6040805190810160405280600b81526020017f49276d20726561647921210000000000000000000000000000000000000000008152506000908051906020019061005a929190610060565b50610105565b828054600181600116156101000203166002900490600052602060002090601f016020900481019282601f106100a157805160ff19168380011785556100cf565b828001600101855582156100cf579182015b828111156100ce5782518255916020019190600101906100b3565b5b5090506100dc91906100e0565b5090565b61010291905b808211156100fe5760008160009055506001016100e6565b5090565b90565b6102e3806101146000396000f30060606040526004361061004c576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff16806349da5de414610051578063ca4c3a41146100ae575b600080fd5b341561005c57600080fd5b6100ac600480803590602001908201803590602001908080601f0160208091040260200160405190810160405280939291908181526020018383808284378201915050505050509190505061013c565b005b34156100b957600080fd5b6100c1610156565b6040518080602001828103825283818151815260200191508051906020019080838360005b838110156101015780820151818401526020810190506100e6565b50505050905090810190601f16801561012e5780820380516001836020036101000a031916815260200191505b509250505060405180910390f35b80600090805190602001906101529291906101fe565b5050565b61015e61027e565b60008054600181600116156101000203166002900480601f0160208091040260200160405190810160405280929190818152602001828054600181600116156101000203166002900480156101f45780601f106101c9576101008083540402835291602001916101f4565b820191906000526020600020905b8154815290600101906020018083116101d757829003601f168201915b5050505050905090565b828054600181600116156101000203166002900490600052602060002090601f016020900481019282601f1061023f57805160ff191683800117855561026d565b8280016001018555821561026d579182015b8281111561026c578251825591602001919060010190610251565b5b50905061027a9190610292565b5090565b602060405190810160405280600081525090565b6102b491905b808211156102b0576000816000905550600101610298565b5090565b905600a165627a7a72305820942b20c01fcdf8e23357936773cd7f98ccef042f7f447691eac916504b932aa20029' }
```

**Comment by soudegesu** [comment]
トランザクションデータの内容に関しては以下
https://qiita.com/takeoworks/items/86cc25f058dbae794017

**Comment by soudegesu** [comment]
`blockHash` はトランザクションブロックのハッシュ

**Comment by soudegesu** [comment]
```
{ number: 3,
  hash: '0x308ce73cf2786389d8fc8f30c96253542239ece8febf75ab4bdb3cb3b7c341c6',
  parentHash: '0xee0a2ea53baf81a149480563831d6f5415b9ad768b81b324daf2f77cdbd93ae4',
  nonce: '0x0',
  sha3Uncles: '0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347',
  logsBloom: '0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
  transactionsRoot: '0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421',
  stateRoot: '0xd3faa518af2e76f25b7687eafdb933304006e32c7244e0b93621fee355ce177d',
  receiptsRoot: '0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421',
  miner: '0x0000000000000000000000000000000000000000',
  difficulty: BigNumber { s: 1, e: 0, c: [ 0 ] },
  totalDifficulty: BigNumber { s: 1, e: 0, c: [ 0 ] },
  extraData: '0x0',
  size: 1000,
  gasLimit: 6721975,
  gasUsed: 284156,
  timestamp: 1520379164,
  transactions:
   [ '0x4c83faddddcccbe091e826184f7f0ac74ba3fa9a4abaee3609974dcdb8113234' ],
  uncles: [] }
```

**Comment by soudegesu** [comment]
1Weiは何Etherか調べる時に使う
https://converter.murkin.me/

**Comment by soudegesu** [comment]
viewがついているものはgasを消費しない
```
    function getGreetings() public view returns (string) {
        return message;
    }

```

**Comment by soudegesu** [comment]
これはlocalのdbから情報をフェッチしているだけであるから

**Comment by soudegesu** [comment]
普通の処理はgasを使っていることがわかる
```
truffle(ganache)> app.setGreetings("Value is chnaged!!", {from: web3.eth.accounts[1]})
{ tx: '0x2c4bd91b347e03ef1b2d4e3009b8daf89ef42f5df46248d38fd885e5958f1686',
  receipt:
   { transactionHash: '0x2c4bd91b347e03ef1b2d4e3009b8daf89ef42f5df46248d38fd885e5958f1686',
     transactionIndex: 0,
     blockHash: '0x642fba7c899eb9ec5b56adc1a8796672bbc642bb8115712b8250356b4146dbe0',
     blockNumber: 5,
     gasUsed: 33864,
     cumulativeGasUsed: 33864,
     contractAddress: null,
     logs: [],
     status: 1 },
  logs: [] }
```

**Comment by soudegesu** [comment]
contractのステートを変化させたい時はgasを必ず支払う必要がある

**Comment by soudegesu** [comment]
https://etherscan.io/opcode-tool
でトランザクションデータをコピペし、デコードするとめっちゃ出る
```
[1] PUSH1 0x60 
[3] PUSH1 0x40 
[4] MSTORE 
[5] CALLVALUE 
[6] ISZERO 
[9] PUSH2 0x000f 
[10] JUMPI 
[12] PUSH1 0x00 
[13] DUP1 
[14] 'fd'(Unknown Opcode) 
[15] JUMPDEST 
[17] PUSH1 0x40 
[18] DUP1 
[19] MLOAD 
[20] SWAP1 
[21] DUP2 
[22] ADD 
```

**Comment by soudegesu** [comment]
OPコードといってEthereumのEVMの動作を実行するコード
https://ethereum-japan.net/wiki/opcode/

**Comment by soudegesu** [comment]
OPCODEのgasの複雑さ計算に依存する命令たちになる

**Comment by soudegesu** [comment]
Ethereumのイエローペーパーに記載されている
https://ethereum.github.io/yellowpaper/paper.pdf

**Comment by soudegesu** [comment]
表を抜粋するとこう
```
operations that a transaction may effect.
Name Value Description*
Gzero 0 Nothing paid for operations of the set Wzero.
Gbase 2 Amount of gas to pay for operations of the set Wbase.
Gverylow 3 Amount of gas to pay for operations of the set Wverylow.
Glow 5 Amount of gas to pay for operations of the set Wlow.
Gmid 8 Amount of gas to pay for operations of the set Wmid.
Ghigh 10 Amount of gas to pay for operations of the set Whigh.
Gextcode 700 Amount of gas to pay for operations of the set Wextcode.
Gbalance 400 Amount of gas to pay for a BALANCE operation.
Gsload 200 Paid for a SLOAD operation.
Gjumpdest 1 Paid for a JUMPDEST operation.
Gsset 20000 Paid for an SSTORE operation when the storage value is set to non-zero from zero.
Gsreset 5000 Paid for an SSTORE operation when the storage value’s zeroness remains unchanged or
is set to zero.
Rsclear 15000 Refund given (added into refund counter) when the storage value is set to zero from
non-zero.
Rselfdestruct 24000 Refund given (added into refund counter) for self-destructing an account.
Gselfdestruct 5000 Amount of gas to pay for a SELFDESTRUCT operation.
Gcreate 32000 Paid for a CREATE operation.
Gcodedeposit 200 Paid per byte for a CREATE operation to succeed in placing code into state.
Gcall 700 Paid for a CALL operation.
Gcallvalue 9000 Paid for a non-zero value transfer as part of the CALL operation.
Gcallstipend 2300 A stipend for the called contract subtracted from Gcallvalue for a non-zero value transfer.
Gnewaccount 25000 Paid for a CALL or SELFDESTRUCT operation which creates an account.
Gexp 10 Partial payment for an EXP operation.
Gexpbyte 50 Partial payment when multiplied by dlog256(exponent)e for the EXP operation.
Gmemory 3 Paid for every additional word when expanding memory.
Gtxcreate 32000 Paid by all contract-creating transactions after the Homestead transition.
Gtxdatazero 4 Paid for every zero byte of data or code for a transaction.
Gtxdatanonzero 68 Paid for every non-zero byte of data or code for a transaction.
Gtransaction 21000 Paid for every transaction.
Glog 375 Partial payment for a LOG operation.
Glogdata 8 Paid for each byte in a LOG operation’s data.
Glogtopic 375 Paid for each topic of a LOG operation.
Gsha3 30 Paid for each SHA3 operation.
Gsha3word 6 Paid for each word (rounded up) for input data to a SHA3 operation.
Gcopy 3 Partial payment for *COPY operations, multiplied by words copied, rounded up.
Gblockhash 20 Payment for BLOCKHASH operation.
Gquaddivisor 100 The quadratic coefficient of the input sizes of the exponentiation-over-modulo precompiled
contrac
```

**Comment by soudegesu** [comment]
扱うデータ型によってcomplexityが変わってくるので注意が必要

**Comment by soudegesu** [comment]
別アカウントに送金してみる
```
truffle(ganache)> web3.eth.sendTransaction({from: web3.eth.accounts[0], to: web3.eth.accounts[1], value:web3.toWei(5, "ether")})
'0x046714fb412724c656250e5856bbb83469e2811b5d710bfa3c515606f5ff938a'
```

**Comment by soudegesu** [comment]
`送金された` というトランザクションが生成された

**Comment by soudegesu** [comment]
トランザクションの詳細を見ると、Etherの送金にもGASが1かかっているものの、Ganacheでは小数点以下を丸めてしまっているため、減っていないように見えるので注意

**Comment by soudegesu** [comment]
```
truffle(ganache)> web3.eth.getBalance(web3.eth.accounts[0]).toNumber()
94999999999999980000
```

**Comment by soudegesu** [comment]
payable という謎の型が出てきた
```
function buyArticle() payable public
```

**Comment by soudegesu** [comment]
`payable` を指定するとetherを送れる

**Comment by soudegesu** [comment]
以下の4種類がある
```
throw
assert
require
revert
```

**Comment by soudegesu** [comment]
1. 呼び出し元に返金処理を行う
2. 状態の変化を元に戻す
3. 関数の実行が途中で中断され、これ以上のgasを消費しない
4. gasが利用しつくされたけど、sender側に通知がされていない
5. REVERTのopcodeが返却されてしまっている

**Comment by soudegesu** [comment]
seller.transfer(msg.value);
の `transfer` は solidity から提供されているが、REVERTを投げることがある。(sendする数字が大き過ぎる場合とか)

**Comment by soudegesu** [comment]
処理をミスるとこんな感じでエラーが出る
```
truffle(ganache)> app.buyArticle({from: web3.eth.accounts[2], value:web3.toWei(5, "ether")})
Error: VM Exception while processing transaction: revert
    at Object.InvalidResponse (/Users/xxxxx/private/chainlist-sample/node_modules/truffle/build/cli.bundled.js:41484:16)
    at /Users/xxxxx/private/chainlist-sample/node_modules/truffle/build/cli.bundled.js:329530:36
    at /Users/xxxxx/private/chainlist-sample/node_modules/truffle/build/cli.bundled.js:325200:9
    at XMLHttpRequest.request.onreadystatechange (/Users/xxxxx/private/chainlist-sample/node_modules/truffle/build/cli.bundled.js:328229:7)
    at XMLHttpRequestEventTarget.dispatchEvent (/Users/xxxxx/private/chainlist-sample/node_modules/truffle/build/cli.bundled.js:176415:18)
    at XMLHttpRequest._setReadyState (/Users/xxxxx/private/chainlist-sample/node_modules/truffle/build/cli.bundled.js:176705:12)
    at XMLHttpRequest._onHttpResponseEnd (/Users/xxxxx/private/chainlist-sample/node_modules/truffle/build/cli.bundled.js:176860:12)
```

**Comment by soudegesu** [comment]
`truffle` にはデバッガが付いている
```
debug 'トランザクションハッシュ値'
```

**Comment by soudegesu** [comment]
デバッグモードでひたすらEnterを押していくとエラーになった箇所がわかる

```
debug(ganache:0x0d2d839b...)>

ChainList.sol | 0xb529f14aa8096f943177c09ca294ad66d2e08b1f:

56:
57:     // we check that the value sent corresponds to the price od the article
58:     require(msg.value == price);
                ^^^^^^^^^^^^^^^^^^

debug(ganache:0x0d2d839b...)>

ChainList.sol | 0xb529f14aa8096f943177c09ca294ad66d2e08b1f:

56:
57:     // we check that the value sent corresponds to the price od the article
58:     require(msg.value == price);
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^

debug(ganache:0x0d2d839b...)>

Transaction halted with a RUNTIME ERROR.

This is likely due to an intentional halting expression, like assert(), require() or revert(). It can also be due to out-of-gas exceptions. Please inspect your transaction parameters and contract code to determine the meaning of this error.
```
